[WIP][BREAKING] Transform module to ESM
SAP/ui5-logger pull request #306
Opened 2022-07-29 20:48 UTC by RandomByte

2022-10-20 13:55 UTC, RandomByte commented
LGTM

2022-10-21 06:55 UTC, flovogt requested changes

2022-10-21 06:55 UTC, flovogt commented on jsdoc.json
> +	"plugins": [],
`jsdoc-plugin.cjs` is missing here. has no effect currently because logger has no public API but this might change, so we should activate it

2022-10-24 04:43 UTC, flovogt approved these changes

2022-10-24 04:43 UTC, flovogt commented on jsdoc.json
> +	"plugins": [],
Done

2022-10-24 12:13 UTC, merged