[INTERNAL] Enhance Dependabot configuration to cover also v2 branch
SAP/ui5-logger pull request #326
Opened 2022-10-25 05:56 UTC by flovogt

2022-10-25 06:32 UTC, matz3 requested changes

2022-10-25 06:32 UTC, matz3 commented on .github/dependabot.yml
> +  target-branch: "main"
If I understand the docs correctly, target-branch should not be provided for the default branch as this prevents the settings to be used for security updates: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch

2022-10-25 06:51 UTC, flovogt commented on .github/dependabot.yml
> +  target-branch: "main"
> Use target-branch to specify a different branch for manifest files and for pull requests. When you use this option, the settings for this package manager will no longer affect any pull requests raised for security updates.

Does this mean in general no security updates?

2022-10-25 07:07 UTC, matz3 commented on .github/dependabot.yml
> +  target-branch: "main"
I think it just means the settings are not considered for them.

2022-11-03 16:54 UTC, matz3 approved these changes

2022-11-04 05:11 UTC, flovogt commented on .github/dependabot.yml
> +  target-branch: "main"
`target-branch` is removed from the main branch config

2022-11-04 05:11 UTC, merged